// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from "./client";
import { client } from "./client.gen";
import type {
  AddCartData,
  AddCartErrors,
  AddCartResponses,
  AddProductData,
  AddProductErrors,
  AddProductResponses,
  AddUserData,
  AddUserErrors,
  AddUserResponses,
  DeleteCartData,
  DeleteCartErrors,
  DeleteCartResponses,
  DeleteProductData,
  DeleteProductErrors,
  DeleteProductResponses,
  DeleteUserData,
  DeleteUserErrors,
  DeleteUserResponses,
  GetAllCartsData,
  GetAllCartsErrors,
  GetAllCartsResponses,
  GetAllProductsData,
  GetAllProductsErrors,
  GetAllProductsResponses,
  GetAllUsersData,
  GetAllUsersErrors,
  GetAllUsersResponses,
  GetCartByIdData,
  GetCartByIdErrors,
  GetCartByIdResponses,
  GetProductByIdData,
  GetProductByIdErrors,
  GetProductByIdResponses,
  GetUserByIdData,
  GetUserByIdErrors,
  GetUserByIdResponses,
  LoginUserData,
  LoginUserErrors,
  LoginUserResponses,
  UpdateCartData,
  UpdateCartErrors,
  UpdateCartResponses,
  UpdateProductData,
  UpdateProductErrors,
  UpdateProductResponses,
  UpdateUserData,
  UpdateUserErrors,
  UpdateUserResponses,
} from "./types.gen";

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
> = Options2<TData, ThrowOnError> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>;
};

/**
 * Get all products
 *
 * Retrieve a list of all available products.
 */
export const getAllProducts = <ThrowOnError extends boolean = false>(
  options?: Options<GetAllProductsData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    GetAllProductsResponses,
    GetAllProductsErrors,
    ThrowOnError
  >({
    url: "/products",
    ...options,
  });
};

/**
 * Add a new product
 *
 * Create a new product.
 */
export const addProduct = <ThrowOnError extends boolean = false>(
  options: Options<AddProductData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    AddProductResponses,
    AddProductErrors,
    ThrowOnError
  >({
    url: "/products",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Delete a product
 *
 * Delete a specific product by ID.
 */
export const deleteProduct = <ThrowOnError extends boolean = false>(
  options: Options<DeleteProductData, ThrowOnError>,
) => {
  return (options.client ?? client).delete<
    DeleteProductResponses,
    DeleteProductErrors,
    ThrowOnError
  >({
    url: "/products/{id}",
    ...options,
  });
};

/**
 * Get a single product
 *
 * Retrieve details of a specific product by ID.
 */
export const getProductById = <ThrowOnError extends boolean = false>(
  options: Options<GetProductByIdData, ThrowOnError>,
) => {
  return (options.client ?? client).get<
    GetProductByIdResponses,
    GetProductByIdErrors,
    ThrowOnError
  >({
    url: "/products/{id}",
    ...options,
  });
};

/**
 * Update a product
 *
 * Update an existing product by ID.
 */
export const updateProduct = <ThrowOnError extends boolean = false>(
  options: Options<UpdateProductData, ThrowOnError>,
) => {
  return (options.client ?? client).put<
    UpdateProductResponses,
    UpdateProductErrors,
    ThrowOnError
  >({
    url: "/products/{id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Get all carts
 *
 * Retrieve a list of all available carts.
 */
export const getAllCarts = <ThrowOnError extends boolean = false>(
  options?: Options<GetAllCartsData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    GetAllCartsResponses,
    GetAllCartsErrors,
    ThrowOnError
  >({
    url: "/carts",
    ...options,
  });
};

/**
 * Add a new cart
 *
 * Create a new cart.
 */
export const addCart = <ThrowOnError extends boolean = false>(
  options: Options<AddCartData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    AddCartResponses,
    AddCartErrors,
    ThrowOnError
  >({
    url: "/carts",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Delete a cart
 *
 * Delete a specific cart by ID.
 */
export const deleteCart = <ThrowOnError extends boolean = false>(
  options: Options<DeleteCartData, ThrowOnError>,
) => {
  return (options.client ?? client).delete<
    DeleteCartResponses,
    DeleteCartErrors,
    ThrowOnError
  >({
    url: "/carts/{id}",
    ...options,
  });
};

/**
 * Get a single cart
 *
 * Retrieve details of a specific cart by ID.
 */
export const getCartById = <ThrowOnError extends boolean = false>(
  options: Options<GetCartByIdData, ThrowOnError>,
) => {
  return (options.client ?? client).get<
    GetCartByIdResponses,
    GetCartByIdErrors,
    ThrowOnError
  >({
    url: "/carts/{id}",
    ...options,
  });
};

/**
 * Update a cart
 *
 * Update an existing cart by ID.
 */
export const updateCart = <ThrowOnError extends boolean = false>(
  options: Options<UpdateCartData, ThrowOnError>,
) => {
  return (options.client ?? client).put<
    UpdateCartResponses,
    UpdateCartErrors,
    ThrowOnError
  >({
    url: "/carts/{id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Get all users
 *
 * Retrieve a list of all users.
 */
export const getAllUsers = <ThrowOnError extends boolean = false>(
  options?: Options<GetAllUsersData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    GetAllUsersResponses,
    GetAllUsersErrors,
    ThrowOnError
  >({
    url: "/users",
    ...options,
  });
};

/**
 * Add a new user
 *
 * Create a new user.
 */
export const addUser = <ThrowOnError extends boolean = false>(
  options: Options<AddUserData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    AddUserResponses,
    AddUserErrors,
    ThrowOnError
  >({
    url: "/users",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Delete a user
 *
 * Delete a specific user by ID.
 */
export const deleteUser = <ThrowOnError extends boolean = false>(
  options: Options<DeleteUserData, ThrowOnError>,
) => {
  return (options.client ?? client).delete<
    DeleteUserResponses,
    DeleteUserErrors,
    ThrowOnError
  >({
    url: "/users/{id}",
    ...options,
  });
};

/**
 * Get a single user
 *
 * Retrieve details of a specific user by ID.
 */
export const getUserById = <ThrowOnError extends boolean = false>(
  options: Options<GetUserByIdData, ThrowOnError>,
) => {
  return (options.client ?? client).get<
    GetUserByIdResponses,
    GetUserByIdErrors,
    ThrowOnError
  >({
    url: "/users/{id}",
    ...options,
  });
};

/**
 * Update a user
 *
 * Update an existing user by ID.
 */
export const updateUser = <ThrowOnError extends boolean = false>(
  options: Options<UpdateUserData, ThrowOnError>,
) => {
  return (options.client ?? client).put<
    UpdateUserResponses,
    UpdateUserErrors,
    ThrowOnError
  >({
    url: "/users/{id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Login
 *
 * Authenticate a user.
 */
export const loginUser = <ThrowOnError extends boolean = false>(
  options: Options<LoginUserData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    LoginUserResponses,
    LoginUserErrors,
    ThrowOnError
  >({
    url: "/auth/login",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};
