// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: "https://fakestoreapi.com" | (string & {});
};

export type Product = {
  id?: number;
  title?: string;
  price?: number;
  description?: string;
  category?: string;
  image?: string;
};

export type Cart = {
  id?: number;
  userId?: number;
  products?: Array<Product>;
};

export type User = {
  id?: number;
  username?: string;
  email?: string;
  password?: string;
};

export type Login = {
  username?: string;
  password?: string;
};

export type LoginResponse = {
  token?: string;
};

export type GetAllProductsData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/products";
};

export type GetAllProductsErrors = {
  /**
   * Bad request
   */
  400: unknown;
};

export type GetAllProductsResponses = {
  /**
   * Success
   */
  200: Array<Product>;
};

export type GetAllProductsResponse =
  GetAllProductsResponses[keyof GetAllProductsResponses];

export type AddProductData = {
  body: Product;
  path?: never;
  query?: never;
  url: "/products";
};

export type AddProductErrors = {
  /**
   * Bad request
   */
  400: unknown;
};

export type AddProductResponses = {
  /**
   * Product created successfully
   */
  201: Product;
};

export type AddProductResponse = AddProductResponses[keyof AddProductResponses];

export type DeleteProductData = {
  body?: never;
  path: {
    id: number;
  };
  query?: never;
  url: "/products/{id}";
};

export type DeleteProductErrors = {
  /**
   * Bad request
   */
  400: unknown;
};

export type DeleteProductResponses = {
  /**
   * Product deleted successfully
   */
  200: unknown;
};

export type GetProductByIdData = {
  body?: never;
  path: {
    id: number;
  };
  query?: never;
  url: "/products/{id}";
};

export type GetProductByIdErrors = {
  /**
   * Bad request
   */
  400: unknown;
};

export type GetProductByIdResponses = {
  /**
   * Success
   */
  200: Product;
};

export type GetProductByIdResponse =
  GetProductByIdResponses[keyof GetProductByIdResponses];

export type UpdateProductData = {
  body: Product;
  path: {
    id: number;
  };
  query?: never;
  url: "/products/{id}";
};

export type UpdateProductErrors = {
  /**
   * Bad request
   */
  400: unknown;
};

export type UpdateProductResponses = {
  /**
   * Product updated successfully
   */
  200: Product;
};

export type UpdateProductResponse =
  UpdateProductResponses[keyof UpdateProductResponses];

export type GetAllCartsData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/carts";
};

export type GetAllCartsErrors = {
  /**
   * Bad request
   */
  400: unknown;
};

export type GetAllCartsResponses = {
  /**
   * Success
   */
  200: Array<Cart>;
};

export type GetAllCartsResponse =
  GetAllCartsResponses[keyof GetAllCartsResponses];

export type AddCartData = {
  body: Cart;
  path?: never;
  query?: never;
  url: "/carts";
};

export type AddCartErrors = {
  /**
   * Bad request
   */
  400: unknown;
};

export type AddCartResponses = {
  /**
   * Cart created successfully
   */
  201: Cart;
};

export type AddCartResponse = AddCartResponses[keyof AddCartResponses];

export type DeleteCartData = {
  body?: never;
  path: {
    id: number;
  };
  query?: never;
  url: "/carts/{id}";
};

export type DeleteCartErrors = {
  /**
   * Bad request
   */
  400: unknown;
};

export type DeleteCartResponses = {
  /**
   * Cart deleted successfully
   */
  200: unknown;
};

export type GetCartByIdData = {
  body?: never;
  path: {
    id: number;
  };
  query?: never;
  url: "/carts/{id}";
};

export type GetCartByIdErrors = {
  /**
   * Bad request
   */
  400: unknown;
};

export type GetCartByIdResponses = {
  /**
   * Success
   */
  200: Cart;
};

export type GetCartByIdResponse =
  GetCartByIdResponses[keyof GetCartByIdResponses];

export type UpdateCartData = {
  body: Cart;
  path: {
    id: number;
  };
  query?: never;
  url: "/carts/{id}";
};

export type UpdateCartErrors = {
  /**
   * Bad request
   */
  400: unknown;
};

export type UpdateCartResponses = {
  /**
   * Cart updated successfully
   */
  200: Cart;
};

export type UpdateCartResponse = UpdateCartResponses[keyof UpdateCartResponses];

export type GetAllUsersData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/users";
};

export type GetAllUsersErrors = {
  /**
   * Bad request
   */
  400: unknown;
};

export type GetAllUsersResponses = {
  /**
   * Success
   */
  200: Array<User>;
};

export type GetAllUsersResponse =
  GetAllUsersResponses[keyof GetAllUsersResponses];

export type AddUserData = {
  body: User;
  path?: never;
  query?: never;
  url: "/users";
};

export type AddUserErrors = {
  /**
   * Bad request
   */
  400: unknown;
};

export type AddUserResponses = {
  /**
   * User created successfully
   */
  201: User;
};

export type AddUserResponse = AddUserResponses[keyof AddUserResponses];

export type DeleteUserData = {
  body?: never;
  path: {
    id: number;
  };
  query?: never;
  url: "/users/{id}";
};

export type DeleteUserErrors = {
  /**
   * Bad request
   */
  400: unknown;
};

export type DeleteUserResponses = {
  /**
   * User deleted successfully
   */
  200: unknown;
};

export type GetUserByIdData = {
  body?: never;
  path: {
    id: number;
  };
  query?: never;
  url: "/users/{id}";
};

export type GetUserByIdErrors = {
  /**
   * Bad request
   */
  400: unknown;
};

export type GetUserByIdResponses = {
  /**
   * Success
   */
  200: User;
};

export type GetUserByIdResponse =
  GetUserByIdResponses[keyof GetUserByIdResponses];

export type UpdateUserData = {
  body: User;
  path: {
    id: number;
  };
  query?: never;
  url: "/users/{id}";
};

export type UpdateUserErrors = {
  /**
   * Bad request
   */
  400: unknown;
};

export type UpdateUserResponses = {
  /**
   * User updated successfully
   */
  200: User;
};

export type UpdateUserResponse = UpdateUserResponses[keyof UpdateUserResponses];

export type LoginUserData = {
  body: Login;
  path?: never;
  query?: never;
  url: "/auth/login";
};

export type LoginUserErrors = {
  /**
   * Bad request
   */
  400: unknown;
};

export type LoginUserResponses = {
  /**
   * Login successful
   */
  200: LoginResponse;
};

export type LoginUserResponse = LoginUserResponses[keyof LoginUserResponses];
